# SPDX-License-Identifier: GPL-3.0-only
name: Build

env:
  KERNEL_GITHUB_REPOSITORY: "okias/linux"
  KERNEL_NAME: qcom-apq8064
  KBUILD_DEFCONFIG: qcom_apq8064_defconfig
  CROSS_COMPILE: arm-linux-gnueabihf- # build for armv7
  ARCH_SPEC_PKGS: crossbuild-essential-armhf
  ARCH: arm # build for armv7

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        kernel: [v4.14, v4.19, v5.4, v5.10, next]
    runs-on: ubuntu-latest
    env:
      TUXMAKE_EXTRA_OPTS: "--kconfig-add CONFIG_GENERIC_IRQ_DEBUGFS=y" # for debugging, set what you need
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: ${{ env.KERNEL_GITHUB_REPOSITORY }}
          ref: ${{ env.KERNEL_NAME }}-${{ matrix.kernel }}
          path: linux
      - name: Build
        run: |
          sudo apt-get -qq update > /dev/null
          sudo apt-get -qq install -y --no-install-recommends -o=Dpkg::Use-Pty=0 ${{ env.ARCH_SPEC_PKGS }} git build-essential binutils-multiarch device-tree-compiler fakeroot libncurses5-dev libssl-dev ccache bison flex libelf-dev dwarves python3-pip socat > /dev/null
          pip3 install -U --user tuxmake
          BRANCH=${{ env.KERNEL_NAME }}-${{ matrix.kernel }} dash ./build.sh
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.KERNEL_NAME }}-${{ matrix.kernel }}"
          prerelease: true
          title: "Build ${{ env.KERNEL_NAME }}-${{ matrix.kernel }}"
          files: |
            *.tar
  dtbs:
    strategy:
      fail-fast: false
      matrix:
        kernel: [next]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: ${{ env.KERNEL_GITHUB_REPOSITORY }}
          ref: ${{ env.KERNEL_NAME }}-${{ matrix.kernel }}
          path: linux
      - name: Build
        run: |
          sudo apt-get -qq update > /dev/null
          sudo apt-get -qq install -y --no-install-recommends -o=Dpkg::Use-Pty=0 ${{ env.ARCH_SPEC_PKGS }} libyaml-dev git build-essential binutils-multiarch device-tree-compiler fakeroot libncurses5-dev libssl-dev ccache bison flex libelf-dev dwarves python3-pip socat > /dev/null
          pip3 install -U --user git+https://github.com/devicetree-org/dt-schema.git@master
          dash ./dtb_check.sh
  dt_bindings_check:
    strategy:
      fail-fast: false
      matrix:
        kernel: [v5.10, next]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: ${{ env.KERNEL_GITHUB_REPOSITORY }}
          ref: ${{ env.KERNEL_NAME }}-${{ matrix.kernel }}
          path: linux
      - name: Build
        run: |
          sudo apt-get -qq update > /dev/null
          sudo apt-get -qq install -y --no-install-recommends -o=Dpkg::Use-Pty=0 ${{ env.ARCH_SPEC_PKGS }} libyaml-dev git build-essential binutils-multiarch device-tree-compiler fakeroot libncurses5-dev libssl-dev ccache bison flex libelf-dev dwarves python3-pip socat > /dev/null
          pip3 install -U --user git+https://github.com/devicetree-org/dt-schema.git@master
          cd linux
          make -j3 dt_binding_check
